on: [push, pull_request]

name: Continuous Integration

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: mymindstorm/setup-emsdk@v14
        with: { version: "3.1.71" }
      - run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
