name: Create a release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  pages: write

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: mymindstorm/setup-emsdk@v14
        with: { version: "3.1.71" }
      - run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - run: cp build/highs.* demo/
      - name: Deploy demo 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: demo
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/highs.wasm
            build/highs.js
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
      - name: publish the package to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
